name: Dotnet Unit Tests

on:
  push:
    paths: [
      .github/workflows/dotnet-unit-test.yaml,
      src/dotnet
    ]

jobs:
  dotnet-unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.x' # Adjust the .NET version as needed

      - name: Install protoc
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      - name: Clone Protovalidate repo
        uses: actions/checkout@v4
        with:
          repository: bufbuild/protovalidate
          path: src/dotnet/ConsoleValidator/proto/protovalidate

      # Get address just using wget?
#      - name: Clone GoogleApi repo
#        uses: actions/checkout@v4
#        with:
#          repository: googleapis/googleapis
#          path: src/dotnet/ConsoleValidator/proto/googleapis

      - name: Compile Protobuf files
        run: |
          protoc \
            -I ./protovalidate/proto/protovalidate \
#            -I=./googleapis \
            --csharp_out=../Models \
            --proto_path=. \
            ./user.proto
        working-directory: src/dotnet/ConsoleValidator/proto

      - name: Install dependencies
        run: dotnet restore
        working-directory: src/dotnet/ConsoleValidator

      - name: Build
        run: dotnet build --configuration Release
        working-directory: src/dotnet/ConsoleValidator

      - name: Run Program
        run: dotnet test
        working-directory: src/dotnet
