name: Dotnet Unit Tests

on:
  push:
    paths: [
      .github/workflows/dotnet-unit-test.yaml,
      src/dotnet/ConsoleValidator
    ]

jobs:
  dotnet-unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.x' # Adjust the .NET version as needed

      - name: Install protoc
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      # - name: Install protoc-gen-csharp plugin
      #   run: |
      #     dotnet tool install --global Google.Protobuf.Tools
      #     export PATH="$PATH:/home/runner/.dotnet/tools"
      #   working-directory: src/dotnet/ConsoleValidator/proto

      - name: Clone Protovalidate repo
        uses: actions/checkout@v4
        with:
          repository: bufbuild/protovalidate
          path: src/dotnet/ConsoleValidator/proto/vendor 

      - name: ls directory
        run: ls src/dotnet/ConsoleValidator/proto/vendor

      - name: Compile Protobuf files
        run: |
          protoc \
            -I ./vendor/protovalidate/proto/protovalidate \
            --csharp_out=../../Models \
            --proto_path=. \
            ./user.proto
        working-directory: src/dotnet/ConsoleValidator/proto

      - name: Install dependencies
        run: dotnet restore
        working-directory: src/dotnet/ConsoleValidator

      - name: Build
        run: dotnet build --configuration Release
        working-directory: src/dotnet/ConsoleValidator

      - name: Run Program
        run: dotnet run
        working-directory: src/dotnet/ConsoleValidator
